#%RAML 1.0 Trait
headers:
      X-Cms-ClientId:
        description: Client Id for validation
        required: true
        type: string
        example: "dereswtdr-tyhnvgb "
      X-Cms-ClientSecret:
        description: Client secret for validation
        required: true
        type: string
        example: "dereswtdr-tyhnvgdb "