#%RAML 1.0 Trait

queryParameters:
  email:
    type: string
    required: false
    example: "abc@gmail.com"
  phoneNumber:
    type: string
    required: false
    example: "45124451"
  phoneCountry:
    type: string
    required: false
    example: "+91"
      
  registrationdate:
    type: string
    required: false
    example: "23-04-1996"
      
      
      