#%RAML 1.0
title: member-system-api

traits:
  clientIdEnforcement : !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-traits/1.0.0/clientidEnforcement-header-traits.raml
  common : !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-traits/1.0.0/common-header-traits.raml
  memberqueryParam: !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-traits/1.0.0/member-quearyParams-traits.raml
types:
  memberDetails: !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-datatypes/1.0.0/members/member-details-datatype.raml
  postMemberdetailsResponse: !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-datatypes/1.0.0/members/member-post-details-response-dataType.raml
  commonError: !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-datatypes/1.0.0/common/error-response-dataType.raml
  patchMemberDetailsRequest: !include /exchange_modules/8bcf9094-8a84-4d10-b7e3-a821f78eadc6/fragment-common-datatypes/1.0.0/members/members-patch-details-datatype.raml
/members:
  /{memberId}:
    patch:
      description: post the customer details
      is:
        - clientIdEnforcement
        - common
      body:
        application/json:
                description: Output message for Get Member Details
                type: patchMemberDetailsRequest
      responses:
          200:
            body:
              application/json:
                description: Output message for Get Member Details
                type: postMemberdetailsResponse
                example: !include /Examples/member-post-response-example.json

          400:
            body:
              application/json:
                description: Error Output message for Get Member Details
                type: commonError
                example: !include /Examples/error-resonse-400-example.json
          401:
            body:
              application/json:
                description: error
                type: commonError
                example: !include /Examples/error-response-401-example.json
          404:
            body:
              application/json:
                description: Resource not found
                type: commonError
                example: !include /Examples/error-response-404-example.json
          500:
            body:
              application/json:
                description: SERVER_ERROR
                type: commonError
                example: !include /Examples/error-response-500-example.json  
    get:
      is:
      - clientIdEnforcement
      - common
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                memberlist:
                  type: array
                  items:
                    type: memberDetails
                    example: !include /Examples/memberDetails-example.json
        400:
          body:
            application/json:
              description: Error Output message for Get Member Details
              type: commonError
              example: !include /Examples/error-resonse-400-example.json
        401:
          body:
            application/json:
              description: error
              type: commonError
              example: !include /Examples/error-response-401-example.json
        404:
          body:
            application/json:
              description: Resource not found
              type: commonError
              example: !include /Examples/error-response-404-example.json
        500:
          body:
            application/json:
              description: SERVER_ERROR
              type: commonError
              example: !include /Examples/error-response-500-example.json
  post:
    description: post the customer details
    is:
      - clientIdEnforcement
      - common
    body:
      application/json:
                description: Output message for Get Member Details
                type: memberDetails
                example: !include /Examples/memberDetails-example.json
                  
    responses:
          200:
            body: 
              application/json:
                description: Output message for Get Member Details
                type: postMemberdetailsResponse
                example: !include /Examples/member-post-response-example.json

          400:
            body:
              application/json:
                description: Error Output message for Get Member Details
                type: commonError
                example: !include /Examples/error-resonse-400-example.json
          401:
            body:
              application/json:
                description: error
                type: commonError
                example: !include /Examples/error-response-401-example.json
          404:
            body:
              application/json:
                description: Resource not found
                type: commonError
                example: !include /Examples/error-response-404-example.json
          500:
            body:
              application/json:
                description: SERVER_ERROR
                type: commonError
                example: !include /Examples/error-response-500-example.json
  get:
    is:
      - clientIdEnforcement
      - common
      - memberqueryParam
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              memberlist:
                type: array
                items:
                  type: memberDetails
                  example: !include /Examples/memberDetails-example.json
      400:
        body:
          application/json:
            description: Error Output message for Get Member Details
            type: commonError
            example: !include /Examples/error-resonse-400-example.json
      401:
        body:
          application/json:
            description: error
            type: commonError
            example: !include /Examples/error-response-401-example.json
      404:
        body:
          application/json:
            description: Resource not found
            type: commonError
            example: !include /Examples/error-response-404-example.json
      500:
        body:
          application/json:
            description: SERVER_ERROR
            type: commonError
            example: !include /Examples/error-response-500-example.json
  /sync:
    post:
      description: post the customer details
      is:
        - clientIdEnforcement
        - common
      body:
        application/json:
                  description: Output message for Get Member Details
                  type: memberDetails
                  example: !include /Examples/memberDetails-example.json
                    
      responses:
            200:
              body: 
                application/json:
                  description: Output message for Get Member Details
                  type: postMemberdetailsResponse
                  example: !include Examples/member-post-response-example.json

            400:
              body:
                application/json:
                  description: Error Output message for Get Member Details
                  type: commonError
                  example: !include /Examples/error-resonse-400-example.json
            401:
              body:
                application/json:
                  description: error
                  type: commonError
                  example: !include /Examples/error-response-401-example.json
            404:
              body:
                application/json:
                  description: Resource not found
                  type: commonError
                  example: !include /Examples/error-response-404-example.json
            500:
              body:
                application/json:
                  description: SERVER_ERROR
                  type: commonError
                  example: !include /Examples/error-response-500-example.json

    
    
      